name: Run SolverEval for ${{inputs.solver}}

on:
  workflow_dispatch:
    inputs:
      solver:
        description: "The solver to run the action for. Must be a valid path like highs/1.6.0"
        required: True

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/build-push-action@v2
      with:
        file: solvers/${{ inputs.solver }}
        tags: ${{inputs.solver}}
        push: false

  runtests:
    - uses: addnab/docker-run-action@v3
      with:
        image: ${{inputs.solver}}
        run: make run